import { useState } from 'react'
import { useTradesData } from '../hooks/useTradesData'

export function TradingTracker({ onBack }: { onBack: () => void }) {
  const [setups, setSetups] = useState(['Opening range breakout', 'Breakout retest', 'VWAP reclaim', 'Trend pullback', 'Failed breakdown', 'Gap fill', 'Range reversal'])
  const [newSetup, setNewSetup] = useState('')
  const { trades, addTrade, deleteTrade } = useTradesData()
  const [ticker, setTicker] = useState('')
  const [setup, setSetup] = useState(setups[0])
  const [direction, setDirection] = useState('Long')
  const [outcome, setOutcome] = useState<'win' | 'loss' | null>(null)
  const [r, setR] = useState('')
  const [note, setNote] = useState('')

  const addSetup = () => { if (newSetup.trim() && !setups.includes(newSetup)) { setSetups([...setups, newSetup]); setNewSetup('') } }
  const deleteSetup = (s: string) => { setSetups(setups.filter(x => x !== s)); if (setup === s) setSetup(setups[0]) }
  const logTrade = async () => { if (!ticker || !outcome) { alert('Fill in ticker'); return }; await addTrade({ ticker: ticker.toUpperCase(), setup, direction, outcome, r: parseFloat(r) || 0, note, date: new Date().toLocaleDateString() }); setTicker('') }

  const stats = { trades: trades.length, wins: trades.filter(t => t.outcome === 'win').length, winRate: trades.length > 0 ? ((trades.filter(t => t.outcome === 'win').length / trades.length) * 100).toFixed(1) : 0, avgR: trades.length > 0 ? (trades.reduce((sum, t) => sum + t.r, 0) / trades.length).toFixed(2) : 0 }

  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto', background: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)', minHeight: '100vh' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '2rem' }}><button onClick={onBack} style={{ background: 'none', border: 'none', color: '#78350f', cursor: 'pointer', fontSize: '1.5rem' }}>←</button><h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', margin: 0, color: '#78350f' }}>📈 Trading Stats</h1></div>
      <div style={{ padding: '2rem', border: '2px solid #92400e', borderRadius: '8px', background: 'white', marginBottom: '2rem', textAlign: 'center' }}><h2 style={{ fontSize: '1.75rem', fontWeight: 'bold', margin: 0, color: '#78350f' }}>I am a profitable trader.</h2></div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem', marginBottom: '2rem' }}><div style={{ padding: '1.5rem', background: 'white', borderRadius: '8px' }}><div style={{ fontSize: '0.75rem', color: '#92400e', textTransform: 'uppercase' }}>Trades</div><div style={{ fontSize: '2rem', fontWeight: 'bold', color: '#78350f' }}>{stats.trades}</div></div><div style={{ padding: '1.5rem', background: 'white', borderRadius: '8px' }}><div style={{ fontSize: '0.75rem', color: '#92400e', textTransform: 'uppercase' }}>Wins</div><div style={{ fontSize: '2rem', fontWeight: 'bold', color: '#22c55e' }}>{stats.wins}</div></div><div style={{ padding: '1.5rem', background: 'white', borderRadius: '8px' }}><div style={{ fontSize: '0.75rem', color: '#92400e', textTransform: 'uppercase' }}>Win Rate</div><div style={{ fontSize: '2rem', fontWeight: 'bold' }}>{stats.winRate}%</div></div><div style={{ padding: '1.5rem', background: 'white', borderRadius: '8px' }}><div style={{ fontSize: '0.75rem', color: '#92400e', textTransform: 'uppercase' }}>Avg R</div><div style={{ fontSize: '2rem', fontWeight: 'bold' }}>{stats.avgR}</div></div></div>
      <div style={{ padding: '2rem', background: 'white', borderRadius: '8px', marginBottom: '2rem' }}><h3 style={{ fontSize: '1rem', fontWeight: 'bold', marginBottom: '1rem', color: '#78350f', textTransform: 'uppercase' }}>Your Strategies</h3><div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1rem' }}>{setups.map(s => <div key={s} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', background: '#f9fafb', borderRadius: '20px', border: '1px solid #ddd' }}><span style={{ fontSize: '0.875rem', fontWeight: '500' }}>{s}</span><button onClick={() => deleteSetup(s)} style={{ background: 'none', border: 'none', color: '#dc2626', cursor: 'pointer', padding: '0', fontSize: '1rem' }}>×</button></div>)}</div><div style={{ display: 'flex', gap: '0.5rem' }}><input type="text" placeholder="Add new strategy..." value={newSetup} onChange={(e) => setNewSetup(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') addSetup() }} style={{ flex: 1, padding: '0.75rem', border: '1px solid #ddd', borderRadius: '4px' }} /><button onClick={addSetup} style={{ padding: '0.75rem 1.5rem', background: '#78350f', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: '500' }}>Add</button></div></div>
      <div style={{ padding: '2rem', background: 'white', borderRadius: '8px', marginBottom: '2rem' }}><h3 style={{ fontSize: '1rem', fontWeight: 'bold', marginBottom: '1.5rem', color: '#78350f', textTransform: 'uppercase' }}>Log a Trade</h3><input type="text" placeholder="SPY" value={ticker} onChange={(e) => setTicker(e.target.value)} style={{ width: '100%', padding: '0.75rem', border: '1px solid #ddd', borderRadius: '4px', marginBottom: '1rem', fontWeight: 'bold' }} /><select value={setup} onChange={(e) => setSetup(e.target.value)} style={{ width: '100%', padding: '0.75rem', border: '1px solid #ddd', borderRadius: '4px', marginBottom: '1rem' }}>{setups.map(s => <option key={s}>{s}</option>)}</select><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}><button onClick={() => setDirection('Long')} style={{ padding: '0.75rem', background: direction === 'Long' ? '#1f2937' : '#f3f4f6', color: direction === 'Long' ? 'white' : '#1f2937', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>Long</button><button onClick={() => setDirection('Short')} style={{ padding: '0.75rem', background: direction === 'Short' ? '#1f2937' : '#f3f4f6', color: direction === 'Short' ? 'white' : '#1f2937', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>Short</button></div><input type="number" placeholder="R" value={r} onChange={(e) => setR(e.target.value)} step="0.1" style={{ width: '100%', padding: '0.75rem', border: '1px solid #ddd', borderRadius: '4px', marginBottom: '1rem' }} /><textarea placeholder="Note" value={note} onChange={(e) => setNote(e.target.value)} style={{ width: '100%', padding: '0.75rem', border: '1px solid #ddd', borderRadius: '4px', marginBottom: '1rem', minHeight: '60px' }} /><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}><button onClick={() => { setOutcome('win'); setTimeout(() => logTrade(), 0) }} style={{ padding: '1rem', background: '#22c55e', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>✅ Win</button><button onClick={() => { setOutcome('loss'); setTimeout(() => logTrade(), 0) }} style={{ padding: '1rem', background: '#dc2626', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>❌ Loss</button></div></div>
      {trades.length > 0 && <div style={{ padding: '2rem', background: 'white', borderRadius: '8px' }}><h3 style={{ fontSize: '1rem', fontWeight: 'bold', marginBottom: '1rem', color: '#78350f', textTransform: 'uppercase' }}>Recent Trades</h3><div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', maxHeight: '300px', overflowY: 'auto' }}>{trades.map((t) => <div key={t.id} style={{ padding: '0.75rem', background: '#f9fafb', borderRadius: '4px', borderLeft: `4px solid ${t.outcome === 'win' ? '#22c55e' : '#dc2626'}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><div><strong>{t.ticker}</strong> • {t.direction} • {t.setup}</div><div style={{ fontSize: '0.875rem', color: '#666' }}>R: {t.r} • {t.outcome === 'win' ? '✅ Win' : '❌ Loss'}</div></div><button onClick={() => deleteTrade(t.id)} style={{ background: 'none', border: 'none', color: '#dc2626', cursor: 'pointer', fontSize: '1.2rem', padding: '0' }}>×</button></div>)}</div></div>}
    </div>
  )
}